import Head from 'next/head'
import Layout from '../../components/layout'
import { PAGE_DATA } from '../../utils/constants'

type RoutePageProps = {
    title: string,
    children?: JSX.Element | JSX.Element[]
}

export default function Routes({}: RoutePageProps) {
    const title = `${PAGE_DATA.siteDescription}: Routes`
    
    return (
        <Layout title={title}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section>
                <h2>Routes</h2>
            </section>
        </Layout>
    )
}