import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Layout from '../../components/layout'
import { PAGE_DATA } from '../../utils/constants'

type StopProps = {
    title: string,
    children?: JSX.Element | JSX.Element[]
}

export default function Stop({}: StopProps) {
    const { query } = useRouter();
    const title = `${PAGE_DATA.siteDescription}: Stop ${query.id ? query.id : ''}`

    return (
        <Layout title={title}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section>
                <h2>Stop {query.id}</h2>
            </section>
        </Layout>
    )
}