import Head from 'next/head'
import Layout from '../../components/layout'
import { PAGE_DATA } from '../../utils/constants'

type StopPageProps = {
    title: string,
    children?: JSX.Element | JSX.Element[]
}

export default function Stops({}: StopPageProps) {
    const title = `${PAGE_DATA.siteDescription}: Stop`
    return (
        <Layout title={title}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section>
                <h2>Stops</h2>
            </section>
        </Layout>
    )
}