import Head from 'next/head'
import Layout from '../components/layout'
import TabController from '../components/tab-controller'
import RoutesPanel from '../components/routes-panel'
import StopPanel from '../components/stops-panel'
import { PAGE_DATA } from '../utils/constants'

export async function getStaticProps() {
  return {
    props: {}
  }
}

export default function Home({ }) {
  return (
    <Layout title={PAGE_DATA.siteDescription}>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section>
        <h2>{PAGE_DATA.homeTitle}</h2>
        <TabController
          panelObjects={
            [
              {id: 0, label: "Routes", panel: <RoutesPanel />},
              {id: 1, label: "Stop", panel: <StopPanel />},
            ]
          }
        />
      </section>
    </Layout>
  )
}
