import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout, { siteDescription } from '../components/layout'
import utilStyles from '../styles/utils.module.css'

export async function getStaticProps() {
  return {
    props: {}
  }
}

export default function Home({ }) {
  return (
    <Layout title={siteDescription}>
      <Head>
        {/* <title>{title}</title> */}
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className={utilStyles.headingMd}>
        <p>About mark</p>
        <p>(this is a sample)</p>
      </section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
      </section>
    </Layout>
  )
}
