import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Layout, { siteDescription } from '../../components/layout'
import utilStyles from '../../styles/utils.module.css'

type StopProps = {
    title: string,
    children?: JSX.Element | JSX.Element[]
}

export default function Stop({}: StopProps) {
    const { query } = useRouter();
    const title = `${siteDescription}: Stop ${query.id ? query.id : ''}`

    return (
        <Layout title={title}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section className={utilStyles.headingMd}>
                <h2>router</h2>
            </section>
        </Layout>
    )
}